export enum TipoUsuarioEnum{
    USUARIO = "USUARIO",
    USUARIO_ESPECIAL = "ANUNCIANTE",
    ADMINISTRADOR_SISTEMA = "ADMINISTRADOR DE SISTEMA",
    ADMINISTRADOR_CINE = "ADMINISTRADOR DE CINE",


}